In [1]:
import re
import pickle
import pandas as pd
from tqdm import tqdm

In [2]:
def load_obj(name):
    with open(name, 'rb') as f:
        return pickle.load(f)

In [3]:
def obtain_uniq_ddc(code_list):
    ddc_code=[a.split(";") if ";" in a else [a] for a in code_list]
    ddc_code_lst= [item for sublist in ddc_code for item in sublist]
    return set(ddc_code_lst)

In [4]:
def find_number(text):
    text=str(text)
    num = re.findall(r'\d+',text)
    return ";".join(num)

In [5]:
ment=pd.read_csv("Shodhganga_mentorship.csv",sep=",")

In [41]:
ment2=pd.read_csv("Shodhganga_mentorship.csv",sep=",")

In [6]:
pd.unique(ment['DepartmentId']).shape         ##########

(2558,)

In [16]:
sim_dept=load_obj('disambigauted_dept_wid_3991725.pkl')

In [17]:
len(sim_dept)

209

In [18]:
remove = [('department of mechanical engineering','department of chemical engineering'),('department of organic chemistry','department of inorganic chemistry'),('department of chemical engineering','department of mechanicalengineering'),('department of chemical oceanography','department of physical oceanography')]

In [19]:
f_sim_names = [((a[0][0],a[1][0]),(sim_dept[a][0], sim_dept[a][1])) for a in sim_dept if (sim_dept[a][2] >= 10 or sim_dept[a][3] >= 10)]

In [20]:
f_sim_names = [a for a in f_sim_names if a[1] not in remove]

In [21]:
len(f_sim_names)

79

In [22]:
ment['N_DepartmentId'] = ment['DepartmentId']
tmp_dict={}
for a in f_sim_names:
    if a[0][0] in tmp_dict and a[0][1] in tmp_dict:
        ment.loc[(ment['N_DepartmentId'].isin([tmp_dict[a[0][0]], tmp_dict[a[0][1]]])),'N_DepartmentId']= tmp_dict[a[0][0]]
    elif a[0][0] in tmp_dict:
        ment.loc[(ment['N_DepartmentId'].isin([tmp_dict[a[0][0]], a[0][1]])),'N_DepartmentId'] = tmp_dict[a[0][0]]
    elif a[0][1] in tmp_dict:
        ment.loc[(ment['N_DepartmentId'].isin([a[0][0], tmp_dict[a[0][1]]])),'N_DepartmentId'] = a[0][0]
    else:
        tmp_dict[a[0][1]]=a[0][0]
        ment.loc[(ment['N_DepartmentId'].isin([a[0][0], a[0][1]])),'N_DepartmentId'] = a[0][0]

In [23]:
pd.unique(ment['N_DepartmentId']).shape

(2485,)

In [7]:
ment['ddc_subject_code'] = ment['dc.subject.ddc'].apply(lambda x: find_number(x))

In [25]:
ment.columns

Index(['advisorId', 'researcherId', 'advId_1', 'studId_1', 'advisor_name',
       'researcher_name', 'dc.date.submitted[]', 'dc.language.iso[]',
       'dc.publisher.department[]', 'DepartmentId',
       'dc.publisher.institution[]', 'instituteId', 'dc.title[]', 'thesisId',
       'dc.type.degree', 'dc.date.awarded', 'dc.subject.ddc', 'dc.source.uri',
       'dc.description.abstract', 'dc.title.alternative', 'N_DepartmentId',
       'ddc_subject_code'],
      dtype='object')

In [9]:
dept_ddc = ment.groupby(['instituteId','DepartmentId'])['ddc_subject_code'].apply(list).reset_index().copy()

In [11]:
dept_ddc.head()

  instituteId DepartmentId                                   ddc_subject_code
0          I1        D1040  [600;620;621, 600;620;621, 600;620;621, 600;62...
1         I10        D1118                                          [500;530]
2         I10        D1365                               [600, 600, 600, 600]
3         I10        D1373                         [600;610;615, 600;610;615]
4         I10        D1417                                          [600;660]

In [45]:
ment2[(ment2["instituteId"]=="I100") & (ment2["DepartmentId"]=="D1121")]

,advisorId,researcherId,advId_1,studId_1,advisor_name,researcher_name,dc.date.submitted[],dc.language.iso[],dc.publisher.department[],DepartmentId,dc.publisher.institution[],instituteId,dc.title[],thesisId,dc.type.degree,dc.date.awarded,dc.subject.ddc,dc.source.uri,dc.description.abstract,dc.title.alternative
111682,44108,165058,44108,165058,"Deka, S. C.","Badwaik, Laxmikant Shivnath",01-01-2013,eng,department of food processing technology,D1121,Tezpur University,I100,Physicochemical changes in bamboo shoot of ass...,T171093,phd,NaN,600::Technology|660::Chemical engineering|664:...,http://shodhganga.inflibnet.ac.in/,NaN,NaN
111683,44109,155687,44109,155687,"Mahanta, C. L.","Mishra, Poonam",01-01-2014,eng,department of food processing technology,D1121,Tezpur University,I100,Characterization of phenolics extracted from a...,T45172,phd,NaN,600::Technology|660::Chemical engineering|664:...,http://shodhganga.inflibnet.ac.in/,NaN,NaN
111684,44110,165059,44110,165059,"Mahanta, Charu Lata","Purkayastha, Manashi Das",01-01-2014,eng,department of food processing technology,D1121,Tezpur University,I100,Study on the valorization of rapeseed press ca...,T158466,phd,NaN,600::Technology|660::Chemical engineering|664:...,http://shodhganga.inflibnet.ac.in/,NaN,NaN
111685,44111,165060,44111,165060,"Mahanta, Lata","Saikia, Sangeeta",01-01-2014,eng,department of food processing technology,D1121,Tezpur University,I100,Studies on the effects of processing on the qu...,T21140,phd,NaN,600::Technology|660::Chemical engineering|664:...,http://shodhganga.inflibnet.ac.in/,NaN,NaN

In [46]:
ment2[(ment2["instituteId"]=="I100") & (ment2["DepartmentId"]=="D1201")]

,advisorId,researcherId,advId_1,studId_1,advisor_name,researcher_name,dc.date.submitted[],dc.language.iso[],dc.publisher.department[],DepartmentId,dc.publisher.institution[],instituteId,dc.title[],thesisId,dc.type.degree,dc.date.awarded,dc.subject.ddc,dc.source.uri,dc.description.abstract,dc.title.alternative
205028,44109,155687,44109,155687,"Mahanta, C. L.","Mishra, Poonam",01-01-2014,eng,department of food engineering and technology,D1201,Tezpur University,I100,Characterization of phenolics extracted from A...,T83668,phd,NaN,600::Technology|660::Chemical engineering|664:...,http://shodhganga.inflibnet.ac.in/,NaN,NaN
205029,75833,165058,75833,165058,"Deka, Sankar Chandra","Badwaik, Laxmikant Shivnath",01-01-2013,eng,department of food engineering and technology,D1201,Tezpur University,I100,Physicochemical changes in bamboo shoot of Ass...,T111004,phd,NaN,600::Technology|660::Chemical engineering|664:...,http://shodhganga.inflibnet.ac.in/,NaN,NaN
205030,44110,238253,44110,238253,"Mahanta, Charu Lata","Dutta, Himjyoti",01-01-2014,eng,department of food engineering and technology,D1201,Tezpur University,I100,Study on the effects of parboiling on rice and...,T33409,phd,NaN,600::Technology|660::Chemical engineering|664:...,http://shodhganga.inflibnet.ac.in/,NaN,NaN
205031,44110,165059,44110,165059,"Mahanta, Charu Lata","Purkayastha, Manashi Das",01-01-2014,eng,department of food engineering and technology,D1201,Tezpur University,I100,Study on the valorization of rapeseed presscak...,T28536,phd,NaN,600::Technology|660::Chemical engineering|664:...,http://shodhganga.inflibnet.ac.in/,NaN,NaN
205032,44108,238254,44108,238254,"Deka, S. C.","Prerna, Khawas",01-01-2015,eng,department of food engineering and technology,D1201,Tezpur University,I100,Value addition of culinary banana musa abb,T149205,phd,NaN,600::Technology|660::Chemical engineering|664:...,http://shodhganga.inflibnet.ac.in/,NaN,NaN
205033,44108,238255,44108,238255,"Deka, S. C.","Saha, Jayabrata",01-01-2016,eng,department of food engineering and technology,D1201,Tezpur University,I100,Studies on green leafy vegetables and pasta qu...,T42128,phd,NaN,600::Technology|660::Chemical engineering|664:...,http://shodhganga.inflibnet.ac.in/,NaN,NaN
205034,44110,238256,44110,238256,"Mahanta, Charu Lata","Kalita, Dipankar",01-01-2016,eng,department of food engineering and technology,D1201,Tezpur University,I100,Studies on the stability and quality parameter...,T15059,phd,NaN,600::Technology|660::Chemical engineering|664:...,http://shodhganga.inflibnet.ac.in/,NaN,NaN
205035,44108,238257,44108,238257,"Deka, S. C.","Samyor, Duyi",01-01-2017,eng,department of food engineering and technology,D1201,Tezpur University,I100,Development of functional extruded food produc...,T83525,phd,NaN,600::Technology|660::Chemical engineering|664:...,http://shodhganga.inflibnet.ac.in/,NaN,NaN
205036,44108,238258,44108,238258,"Deka, S. C.","Das, Arup Jyoti",01-01-2017,eng,department of food engineering and technology,D1201,Tezpur University,I100,Biochemical and microbiological characterizati...,T175534,phd,01-01-2017,600::Technology|660::Chemical engineering|664:...,http://shodhganga.inflibnet.ac.in/,NaN,NaN
205037,75834,238258,75834,238258,"Miyaji, Tatsuro","Das, Arup Jyoti",01-01-2017,eng,department of food engineering and technology,D1201,Tezpur University,I100,Biochemical and microbiological characterizati...,T175534,phd,01-01-2017,600::Technology|660::Chemical engineering|664:...,http://shodhganga.inflibnet.ac.in/,NaN,NaN
205038,44108,238259,44108,238259,"Deka, S. C.","Sit, Nandan",01-01-2013,eng,department of food engineering and technology,D1201,Tezpur University,I100,Characterization of starch from different Taro...,T192208,phd,NaN,600::Technology|660::Chemical engineering|664:...,http://shodhganga.inflibnet.ac.in/,NaN,NaN

In [12]:
dept_ddc['uniq_ddc_across_dept'] = dept_ddc['ddc_subject_code'].apply(lambda x: obtain_uniq_ddc(x))

In [13]:
dept_ddc['uniq_ddc_across_dept'] = dept_ddc['uniq_ddc_across_dept'].apply(lambda x: sorted(x))

In [14]:
dept_ddc['uniq_ddc_across_dept'] = dept_ddc['uniq_ddc_across_dept'].apply(lambda x: tuple(x))

In [15]:
pd.unique(dept_ddc['uniq_ddc_across_dept'])

array([('600', '620', '621'), ('500', '530'), ('600',),
       ('600', '610', '615'), ('600', '660'), ('600', '610'),
       ('000', '004'), ('600', '660', '664'), ('600', '650', '658'),
       ('600', '620', '624'), ('000', '070'), ('500', '590'),
       ('500', '570', '600', '660'), ('500', '540'), ('600', '620'),
       ('300', '303'), ('300', '330', '333'), ('300', '301'),
       ('500', '510'), ('800', '890', '891'), ('700',),
       ('600', '620', '628'), ('400',), ('300', '370'), ('500', '570'),
       ('300', '330', '332'), ('300', '370', '375'), ('',),
       ('500', '570', '572'), ('700', '790'), ('300', '330'),
       ('300', '360', '362'), ('500', '550', '551'),
       ('300', '360', '368'), ('900',), ('300', '380', '381'),
       ('500', '580'), ('600', '630', '636'), ('100',),
       ('000', '004', '300', '370'), ('', '400'), ('300',),
       ('300', '320'), ('800', '820'), ('400', '490', '491'),
       ('300', '340'), ('400', '490'), ('000', '020'),
       ('600', '620', '623'), ('500', '550'), ('300', '320', '327'),
       ('000', '080', '089'), ('100', '150'), ('600', '640'),
       ('500', '590', '591'), ('600', '610', '611'), ('500',),
       ('400', '490', '491', '500', '520'), ('600', '630'),
       ('300', '350', '355'), ('400', '410'), ('700', '780'),
       ('300', '340', '342'), ('', '300', '303'), ('000', '080'),
       ('700', '720'), ('500', '570', '571'),
       ('100', '150', '300', '301'), ('300', '390', '398'),
       ('800', '805'), ('700', '780', '781'), ('100', '190'),
       ('', '500', '570'), ('600', '650', '657'), ('300', '350'),
       ('500', '570', '577'), ('700', '740', '741'), ('300', '302'),
       ('600', '640', '641'), ('300', '320', '350'),
       ('600', '610', '612'), ('', '300', '380', '381'),
       ('', '600', '640'), ('600', '650'), ('300', '306'),
       ('100', '150', '155'), ('500', '540', '600', '660'),
       ('', '600', '650', '658'), ('600', '680'), ('900', '950'),
       ('200',), ('700', '710', '714'), ('300', '302', '600'),
       ('300', '370', '372'), ('600', '607'), ('200', '290', '297'),
       ('300', '305'), ('900', '950', '956'), ('100', '180', '181'),
       ('900', '910'), ('500', '520'), ('200', '203'),
       ('200', '290', '294'), ('100', '180'), ('600', '660', '662'),
       ('300', '310'), ('700', '790', '798'),
       ('400', '410', '800', '890', '891'), ('500', '570', '576'),
       ('600', '610', '617'), ('200', '210'), ('700', '790', '791'),
       ('', '300', '370'), ('600', '660', '669'), ('600', '670', '677'),
       ('300', '330', '331'), ('', '300', '340'),
       ('', '600', '630', '635'), ('500', '550', '551', '600', '660'),
       ('600', '630', '639'), ('500', '540', '541'),
       ('600', '630', '634'), ('300', '370', '378'),
       ('500', '540', '570'), ('600', '660', '668'),
       ('500', '540', '541', '550', '551'), ('500', '590', '595'),
       ('300', '330', '338'), ('100', '110', '114'),
       ('100', '150', '153'), ('300', '360', '361'), ('800',),
       ('800', '880', '882'), ('600', '610', '616'),
       ('600', '630', '631'), ('600', '630', '638'),
       ('600', '630', '633'), ('800', '809'), ('600', '610', '618'),
       ('300', '360', '363'), ('600', '620', '629'),
       ('500', '530', '537'), ('300', '330', '340'),
       ('600', '630', '632'), ('300', '307'), ('600', '620', '622'),
       ('500', '580', '582'), ('300', '304'), ('700', '740', '745'),
       ('600', '660', '661'), ('', '300', '320'), ('', '500', '540'),
       ('', '500', '590'), ('800', '803'), ('', '300', '320', '327'),
       ('', '600', '680'), ('900', '950', '954'), ('', '900'),
       ('800', '820', '822'), ('300', '330', '335'),
       ('800', '820', '890', '891'), ('600', '610', '614'),
       ('500', '530', '570'), ('600', '630', '635'),
       ('500', '540', '547'), ('500', '530', '538'),
       ('500', '570', '579'), ('600', '610', '613'),
       ('600', '620', '680'), ('300', '301', '370'),
       ('300', '370', '374'), ('200', '260', '261'),
       ('500', '510', '519'), ('600', '630', '637'), ('200', '280'),
       ('400', '490', '491', '800', '890', '891'), ('300', '360'),
       ('300', '320', '323'), ('300', '301', '320'),
       ('200', '220', '221'), ('100', '150', '300', '370'),
       ('300', '370', '371'), ('500', '540', '570', '576'),
       ('300', '360', '364'), ('500', '506'), ('300', '350', '351'),
       ('500', '505'), ('300', '380'), ('100', '107'),
       ('500', '550', '553'), ('500', '590', '600', '660'),
       ('600', '670', '675'), ('000', '020', '025'),
       ('100', '150', '600', '650', '658'), ('600', '690', '691'),
       ('100', '110', '113'), ('100', '110', '118'), ('400', '420'),
       ('', '100', '150'), ('', '300', '330'),
       ('500', '580', '600', '660'), ('800', '890', '895'),
       ('300', '360', '363', '368'), ('', '500', '580'),
       ('300', '360', '362', '500', '550', '551'), ('', '000', '020'),
       ('300', '310', '317'), ('700', '780', '782'),
       ('600', '620', '627'), ('300', '330', '340', '342'),
       ('800', '806'), ('400', '490', '495'), ('', '600', '620'),
       ('', '500', '530'), ('', '600', '610', '615'),
       ('', '600', '620', '621'), ('', '600', '610', '611')], dtype=object)

In [31]:
#dept_ddc_sorted = dept_ddc.sort_values(['DepartmentId'])

In [32]:
dept_ddc[(dept_ddc['instituteId']=='I251') & (dept_ddc['N_DepartmentId']=='D2490')]

,instituteId,N_DepartmentId,ddc_subject_code,uniq_ddc_across_dept
2649,I251,D2490,"[300, 300, 300, 300, 300, 300, 300, 300, 300, ...","(300,)"

In [33]:
dept_ddc['N_DepartmentId_1']=dept_ddc['N_DepartmentId']
uniq_inst = pd.unique(dept_ddc['instituteId'])
for inst in tqdm(uniq_inst):
    inst_data = dept_ddc[dept_ddc['instituteId']==inst]
    if inst_data.shape[0] > 1:
        #print(inst_data)
        uniq_ddc=pd.unique(inst_data['uniq_ddc_across_dept'])
        for ddc in uniq_ddc:
            #print(ddc)
            if len(ddc) > 0:
                sim_deptid = inst_data[inst_data['uniq_ddc_across_dept']==ddc]['N_DepartmentId_1'].tolist()
                #print(sim_deptid)
                dept_ddc.loc[(dept_ddc['instituteId']==inst) & (dept_ddc['uniq_ddc_across_dept']==ddc),'N_DepartmentId_1']=sim_deptid[-1]
            else:
                continue
    else:
        continue

100%|██████████| 367/367 [00:26<00:00, 14.05it/s]

In [35]:
ment1=ment.merge(dept_ddc, left_on=['instituteId', 'N_DepartmentId'], right_on=['instituteId', 'N_DepartmentId'])

In [36]:
pd.unique(ment1['N_DepartmentId_1']).shape

(1440,)

In [29]:
ment1.drop(['advId_1','studId_1','ddc_subject_code_x','ddc_subject_code_y','dc.source.uri'], axis=1, inplace=True)

In [30]:
ment1['dc.date.submitted[]'].fillna(ment1['dc.date.awarded'], inplace=True)

In [31]:
ment1['dc.date.submitted[]'] = pd.to_datetime(ment1['dc.date.submitted[]'],errors='coerce')

In [33]:
ment1.rename(columns={'dc.date.submitted[]': 'date_submitted', 'dc.publisher.department[]': 'publisher_dept','dc.publisher.institution[]':'publisher_institution','dc.title[]':"title"}, inplace=True)

In [9]:
#ment1.columns

In [35]:
ment1.head(10)

,advisorId,researcherId,advisor_name,researcher_name,date_submitted,dc.language.iso[],publisher_dept,DepartmentId,publisher_institution,instituteId,title,thesisId,dc.type.degree,dc.date.awarded,dc.subject.ddc,dc.description.abstract,dc.title.alternative,N_DepartmentId,uniq_ddc_across_dept,N_DepartmentId_1
0,0,38335,"Jose, Joseph","Thoppil, John E.",1998-01-01,eng,department of sacred heart college(thevara). d...,D1321,Mahatma Gandhi University,I251,Chromosome studies and exploration of chemical...,T121508,phd,16-12-1993,500::Natural sciences & mathematics|580::Plant...,NaN,NaN,D129,"(500, 580)",D864
1,24,75938,"Joy, C. M.","Jose, K P.",2002-01-07,eng,department of sacred heart college(thevara).de...,D129,Mahatma Gandhi University,I251,Strategies to improve the quality of spices cu...,T149232,phd,NaN,500::Natural sciences & mathematics|580::Plant...,NaN,NaN,D129,"(500, 580)",D864
2,23,75940,"Joseph, Joy P.","Aruna, A.",2004-01-04,eng,department of sacred heart college(thevara).de...,D129,Mahatma Gandhi University,I251,Studies on micropropagation for conservation o...,T134031,phd,01-04-2005,500::Natural sciences & mathematics|580::Plant...,NaN,NaN,D129,"(500, 580)",D864
3,0,32890,"Jose, Joseph","Joseph, Roy",1998-01-01,eng,department of sacred heart college(thevara).de...,D129,Mahatma Gandhi University,I251,Karyomorphometrical analysis and exploration o...,T172826,phd,NaN,500::Natural sciences & mathematics|580::Plant...,NaN,NaN,D129,"(500, 580)",D864
4,1,75893,"Raju, K. V.","Ancy, V P.",2015-05-29,eng,department of sacred heart college,D2490,Mahatma Gandhi University,I251,Fishing industry in Kerala The perils of inter...,T64215,phd,29-03-2016,300::Social sciences,NaN,NaN,D2490,"(300,)",D432
5,2,75894,"Joseph, K. K.","Sajoy, P B.",2015-08-24,eng,department of sacred heart college,D2490,Mahatma Gandhi University,I251,Savings and investment pattern of stock invest...,T134025,phd,29-03-2016,300::Social sciences,NaN,NaN,D2490,"(300,)",D432
6,3,75895,"Thomas, E. M.","Leema, T G.",2015-07-15,eng,department of sacred heart college,D2490,Mahatma Gandhi University,I251,An economic analysis of Kole cultivation in Ke...,T78956,phd,02-06-2016,300::Social sciences,NaN,NaN,D2490,"(300,)",D432
7,4,75896,"Francis, M. S.","Murali, Soumya",2015-12-28,eng,department of sacred heart college,D2490,Mahatma Gandhi University,I251,Phytochemical and Molecular Systematics of Ari...,T54905,phd,05-11-2016,300::Social sciences,NaN,NaN,D2490,"(300,)",D432
8,4,75897,"Francis, M. S.","Rashmi, T R.",2015-12-28,eng,department of sacred heart college,D2490,Mahatma Gandhi University,I251,Photochemical and Molecular Systematic of Arte...,T115514,phd,05-11-2016,300::Social sciences,NaN,NaN,D2490,"(300,)",D432
9,5,75898,"Karmaly, K. A.","Emiliyamma, K G.",2016-05-03,eng,department of sacred heart college,D2490,Mahatma Gandhi University,I251,Studies on the Taxonomy of Chalcididae Hymenop...,T123679,phd,31-12-2016,300::Social sciences,NaN,NaN,D2490,"(300,)",D432

In [ ]:
ment1[ment1["instituteId"]=="I251"][['dc.publisher.department[]','DepartmentId']].value_counts()

In [ ]:
ment1[ment1["instituteId"]=="I251"].groupby(['N_DepartmentId_1'])['dc.publisher.department[]'].apply(set).reset_index()[40:60].values

In [39]:
pd.unique(ment1[(ment1["instituteId"]=="I251") & (ment1["N_DepartmentId_1"]=="D432")]['publisher_dept'])

array(['department of sacred heart college',
       'department of rajagiri college of social sciences(kalamassery). department of social work',
       'department of rajagiri college of social sciences (kalamassery). department of social work',
       'department of rajagiri college of social sciences',
       'department of rajagiri college of social sciences(kalamassery)',
       'department of rajagiri college of social sciences(kalamassery).',
       'department of rajagiri college of social sciences(kalamassery).college of social science',
       'school of social sciences'], dtype=object)

In [41]:
ment1.to_csv("base_data/final_shodhganga_mentorship.csv",index=False)

In [ ]:
dept_ddc['uniq_ddc_across_dept'][0]==dept_ddc['uniq_ddc_across_dept'][2821]

In [ ]:
dept_ddc.iloc[0,:]

In [ ]:
dept_ddc.iloc[2821,:]

In [ ]:
dept_ddc.columns

In [3]:
ment3=pd.read_csv("base_data/final_shodhganga_mentorship.csv",sep=",")

In [4]:
ment3.columns

Index(['advisorId', 'researcherId', 'advisor_name', 'researcher_name',
       'date_submitted', 'dc.language.iso[]', 'publisher_dept', 'DepartmentId',
       'publisher_institution', 'instituteId', 'title', 'thesisId',
       'dc.type.degree', 'dc.date.awarded', 'dc.subject.ddc',
       'dc.description.abstract', 'dc.title.alternative', 'N_DepartmentId',
       'uniq_ddc_across_dept', 'N_DepartmentId_1'],
      dtype='object')

In [9]:
pd.unique(ment3['N_DepartmentId_1']).shape

(1440,)

In [10]:
pd.unique(ment3['DepartmentId']).shape

(2557,)

In [11]:
ment3.rename(columns={'N_DepartmentId_1': 'DepartmentId', 'DepartmentId': 'N_DepartmentId_1'}, inplace=True)

In [12]:
pd.unique(ment3['N_DepartmentId_1']).shape

(2557,)

In [13]:
pd.unique(ment3['DepartmentId']).shape

(1440,)

In [14]:
ment3.to_csv("./base_data/sodhganga_mentorship_dept_rev.csv", index=False)

In [15]:
ment3.columns

Index(['advisorId', 'researcherId', 'advisor_name', 'researcher_name',
       'date_submitted', 'dc.language.iso[]', 'publisher_dept',
       'N_DepartmentId_1', 'publisher_institution', 'instituteId', 'title',
       'thesisId', 'dc.type.degree', 'dc.date.awarded', 'dc.subject.ddc',
       'dc.description.abstract', 'dc.title.alternative', 'N_DepartmentId',
       'uniq_ddc_across_dept', 'DepartmentId'],
      dtype='object')

In [16]:
ment3.head()

,advisorId,researcherId,advisor_name,researcher_name,date_submitted,dc.language.iso[],publisher_dept,N_DepartmentId_1,publisher_institution,instituteId,title,thesisId,dc.type.degree,dc.date.awarded,dc.subject.ddc,dc.description.abstract,dc.title.alternative,N_DepartmentId,uniq_ddc_across_dept,DepartmentId
0,0,38335,"Jose, Joseph","Thoppil, John E.",1998-01-01,eng,department of sacred heart college(thevara). d...,D1321,Mahatma Gandhi University,I251,Chromosome studies and exploration of chemical...,T121508,phd,16-12-1993,500::Natural sciences & mathematics|580::Plant...,NaN,NaN,D129,"('500', '580')",D864
1,24,75938,"Joy, C. M.","Jose, K P.",2002-01-07,eng,department of sacred heart college(thevara).de...,D129,Mahatma Gandhi University,I251,Strategies to improve the quality of spices cu...,T149232,phd,NaN,500::Natural sciences & mathematics|580::Plant...,NaN,NaN,D129,"('500', '580')",D864
2,23,75940,"Joseph, Joy P.","Aruna, A.",2004-01-04,eng,department of sacred heart college(thevara).de...,D129,Mahatma Gandhi University,I251,Studies on micropropagation for conservation o...,T134031,phd,01-04-2005,500::Natural sciences & mathematics|580::Plant...,NaN,NaN,D129,"('500', '580')",D864
3,0,32890,"Jose, Joseph","Joseph, Roy",1998-01-01,eng,department of sacred heart college(thevara).de...,D129,Mahatma Gandhi University,I251,Karyomorphometrical analysis and exploration o...,T172826,phd,NaN,500::Natural sciences & mathematics|580::Plant...,NaN,NaN,D129,"('500', '580')",D864
4,1,75893,"Raju, K. V.","Ancy, V P.",2015-05-29,eng,department of sacred heart college,D2490,Mahatma Gandhi University,I251,Fishing industry in Kerala The perils of inter...,T64215,phd,29-03-2016,300::Social sciences,NaN,NaN,D2490,"('300',)",D432

In [22]:
advisor_detail=ment3.groupby(['advisorId','advisor_name','instituteId',
                               'DepartmentId'], as_index=False)[['publisher_dept','publisher_institution','date_submitted','title','dc.subject.ddc']].agg(lambda x: list(x))

In [26]:
advisor_detail['publisher_dept']=advisor_detail['publisher_dept'].apply(lambda x : set(x))

In [33]:
advisor_detail.head()

,advisorId,advisor_name,instituteId,DepartmentId,publisher_dept,publisher_institution,date_submitted,title,dc.subject.ddc
0,0,"Jose, Joseph",I251,D432,{department of sacred heart college},[Mahatma Gandhi University],[2009-10-06],[Karyomorphometrical analysis and exploration ...,[300::Social sciences]
1,0,"Jose, Joseph",I251,D617,{faculty of science},"[Mahatma Gandhi University, Mahatma Gandhi Uni...","[1999-01-01, 2001-01-01, 2004-01-01]",[Karyo morphological analysis and exploration ...,"[500::Natural sciences & mathematics, 500::Nat..."
2,0,"Jose, Joseph",I251,D864,{department of sacred heart college(thevara). ...,"[Mahatma Gandhi University, Mahatma Gandhi Uni...","[1998-01-01, 1998-01-01]",[Chromosome studies and exploration of chemica...,[500::Natural sciences & mathematics|580::Plan...
3,1,"Raju, K. V.",I251,D432,{department of sacred heart college},"[Mahatma Gandhi University, Mahatma Gandhi Uni...","[2015-05-29, 2013-08-04, 2009-10-29, 2012-03-08]",[Fishing industry in Kerala The perils of inte...,"[300::Social sciences, 300::Social sciences, 3..."
4,1,"Raju, K. V.",I251,D583,{department of economics},"[Mahatma Gandhi University, Mahatma Gandhi Uni...","[2005-01-02, 2007-01-05]",[Dynamics of export promotion strategies and g...,"[300::Social sciences|330::Economics, 300::Soc..."

In [32]:
advisor_detail.shape

(93389, 9)