<h2>Name refers to same person, which are different (Name Resolution With Thesis) </h2>

In [1]:
import re
import itertools
import pandas as pd
from tqdm import tqdm
import pickle
import json
import spacy
import numpy as np

In [2]:
#folder="dataset_v5/v5_2/"

In [3]:
folder = '../dataset_v5/v5_2/v5_2_2/'

In [4]:
nlp=spacy.load('en_core_web_lg')

In [5]:
tqdm.pandas()

/home/dj/Desktop/Shodhganga_work/venv/lib/python3.7/site-packages/tqdm/std.py:701: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  from pandas import Panel

In [6]:
#ment = pd.read_csv(folder+"joined_stud_adv_shodhganga_ment_with_disamb_ids4_1_2.csv",sep=",")

In [7]:
ment = pd.read_csv(folder+"final_shodhganga_dataset_v5_2_7.csv",sep=",")

In [8]:
ment.columns

Index(['advisorId', 'researcherId', 'advId', 'resId', 'advisor_name',
       'researcher_name', 'publisher_dept', 'DepartmentId',
       'publisher_institution', 'instituteId', 'title', 'thesisId',
       'N_thesisId', 'date_submitted', 'new_date_awarded', 'dc.date.awarded',
       'dc.subject.ddc', 'uniq_ddc_across_dept', 'dc.description.abstract',
       'dc.title.alternative', 'N_DepartmentId_1', 'ddc_code', 'advisor_advId',
       'researcher_resId'],
      dtype='object')

In [9]:
# Researcher which are different when thesisId is consisdered(All other info is same)
#ment[ment[['advId','resId','N_DepartmentId','instituteId','N_thesisId']].duplicated()]

In [10]:
ment.shape

(201477, 24)

In [11]:
type(pd.unique(ment[(ment['resId']==217627)]['dc.date.awarded'])[1])

float

In [12]:
def researcher_dism_thesis(idd, ment):
    tmp = ment[ment['resId']==idd].copy()
    if tmp.shape[0]==1:
        return 'one'
    else:
        date_uniq = pd.unique(tmp['date_submitted'])
        uniq_thesisid = pd.unique(tmp['N_thesisId'])
        uniq_resid = pd.unique(tmp['resId'])
        if uniq_resid.shape[0]==1 and uniq_thesisid.shape[0]==1:
            return 'two'
        elif uniq_resid.shape[0]==1 and date_uniq.shape[0]==1: # uniq_thesisid.shape[0] > 1
            ment.loc[(ment['N_thesisId'].isin(uniq_thesisid)),'N_thesisId'] = uniq_thesisid[0]
            return 'three'     
        elif uniq_resid.shape[0]==1 and uniq_thesisid.shape[0] > 1 and date_uniq.shape[0] > 1 :
            if uniq_thesisid.shape[0] > date_uniq.shape[0]:
                for date in date_uniq:
                    if type(date)==str:
                        tid1=tmp[tmp['date_submitted']==date]['N_thesisId'].values[0]
                        tmp.loc[tmp['date_submitted']==date,'N_thesisId']=tid1
                        ment.loc[((ment['resId']==idd) & (ment['date_submitted']==date)),'N_thesisId']=tid1
                    else:
                        continue
            as_adv = ment[ment['advId']==idd].copy()
            uniq_stud=tmp.groupby(['N_thesisId'])['title'].apply(list).reset_index().copy()
            uniq_stud['title']=uniq_stud['title'].apply(lambda x: x[0])
            #print(uniq_stud['N_thesisId'])
            #as_stud_uniq_thesis = tmp[tmp['N_thesisId'].isin(uniq_thesisid)][['title','N_thesisId']]
            as_adv_uniq_thesis = pd.unique(as_adv['title'])
            if as_adv_uniq_thesis.shape[0] > 0:
                #print('yes')
                score=[]
                for index, stud in uniq_stud.iterrows():
                    score_list = [nlp(stud['title']).similarity(nlp(adv_thesis)) for adv_thesis in as_adv_uniq_thesis]
                    score.append((stud['N_thesisId'], sum(score_list)))
                sorted_score = sorted(score, key=lambda x: x[1],reverse=True)
                #print(sorted_score)
                #max_stud = tmp[tmp['title']==sorted_score[0][0]]
                for index1, stud1 in uniq_stud.iterrows(): 
                    if stud1['N_thesisId'] != sorted_score[0][0]:
                        ment.loc[((ment['resId']==idd) & (ment['N_thesisId']==stud1['N_thesisId'])), 'resId']=max(ment["resId"].max(axis=0), ment["advId"].max(axis=0))+1
                    else:    
                        continue
            else:
                count=1
                uniq_thesisid1=pd.unique(tmp['N_thesisId'])
                #print(uniq_thesisid1)
                for tid in uniq_thesisid1:
                    if count > 1 :
                        ment.loc[((ment['resId']==idd) & (ment['N_thesisId']==tid)),'resId']= max(ment["resId"].max(axis=0), ment["advId"].max(axis=0))+1
                        count += 1
                    else:
                        count += 1
                        continue
        else:
            print("Not Possible")
    return

In [13]:
#ment=ment[(ment["resId"]==76213.0) | (ment["advId"]==76213.0)]#['dc.title[]']

In [14]:
# max(ment[["resId", "advId"]].max(axis=0))

In [15]:
#ment1=ment.copy()

In [16]:
#ment=ment1[(ment1['resId']==217627)].copy()

In [17]:
uniq_resid_all = pd.unique(ment['resId'])

In [18]:
uniq_resid_all.shape  #188854

(188688,)

In [19]:
uniq_resid_series = pd.Series(uniq_resid_all)

In [20]:
tmp = uniq_resid_series.progress_apply(researcher_dism_thesis, args=(ment,))

  5%|▌         | 9738/188688 [00:13<01:40, 1778.25it/s]/home/dj/Desktop/Shodhganga_work/venv/lib/python3.7/site-packages/ipykernel_launcher.py:33: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  7%|▋         | 14088/188688 [00:24<04:51, 599.77it/s]/home/dj/Desktop/Shodhganga_work/venv/lib/python3.7/site-packages/ipykernel_launcher.py:33: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
 16%|█▌        | 29874/188688 [00:44<01:35, 1671.53it/s]/home/dj/Desktop/Shodhganga_work/venv/lib/python3.7/site-packages/ipykernel_launcher.py:33: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
 31%|███       | 57589/188688 [01:09<03:07, 700.81it/s] /home/dj/Desktop/Shodhganga_work/venv/lib/python3.7/site-packages/ipykernel_launcher.py:33: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
 34%|███▎      | 63555/188688 [01:21<04:46, 436.51it/s] /home/dj/Desktop/Shodhganga_work/venv/lib/python3.7/site-packages/ipykernel_launcher.py:33: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
 34%|███▎      | 63622/188688 [01:22<04:25, 471.20it/s]/home/dj/Desktop/Shodhganga_work/venv/lib/python3.7/site-packages/ipykernel_launcher.py:33: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
 42%|████▏     | 79858/188688 [01:35<00:51, 2094.64it/s]/home/dj/Desktop/Shodhganga_work/venv/lib/python3.7/site-packages/ipykernel_launcher.py:33: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
 50%|█████     | 94475/188688 [01:50<06:17, 249.41it/s] /home/dj/Desktop/Shodhganga_work/venv/lib/python3.7/site-packages/ipykernel_launcher.py:33: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
 51%|█████▏    | 96839/188688 [01:52<00:55, 1645.28it/s]/home/dj/Desktop/Shodhganga_work/venv/lib/python3.7/site-packages/ipykernel_launcher.py:33: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
/home/dj/Desktop/Shodhganga_work/venv/lib/python3.7/site-packages/ipykernel_launcher.py:33: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
 67%|██████▋   | 126593/188688 [02:21<01:05, 950.68it/s] /home/dj/Desktop/Shodhganga_work/venv/lib/python3.7/site-packages/ipykernel_launcher.py:33: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
 68%|██████▊   | 127703/188688 [02:27<03:07, 325.14it/s]/home/dj/Desktop/Shodhganga_work/venv/lib/python3.7/site-packages/ipykernel_launcher.py:33: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
 68%|██████▊   | 127746/188688 [02:28<05:09, 196.64it/s]/home/dj/Desktop/Shodhganga_work/venv/lib/python3.7/site-packages/ipykernel_launcher.py:33: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
/home/dj/Desktop/Shodhganga_work/venv/lib/python3.7/site-packages/ipykernel_launcher.py:33: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
 68%|██████▊   | 127824/188688 [02:28<03:41, 274.41it/s]/home/dj/Desktop/Shodhganga_work/venv/lib/python3.7/site-packages/ipykernel_launcher.py:33: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
 72%|███████▏  | 135590/188688 [02:34<00:59, 898.50it/s] /home/dj/Desktop/Shodhganga_work/venv/lib/python3.7/site-packages/ipykernel_launcher.py:33: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
 75%|███████▌  | 141521/188688 [02:42<02:25, 323.07it/s] /home/dj/Desktop/Shodhganga_work/venv/lib/python3.7/site-packages/ipykernel_launcher.py:33: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
 89%|████████▉ | 167869/188688 [03:07<00:13, 1598.51it/s]/home/dj/Desktop/Shodhganga_work/venv/lib/python3.7/site-packages/ipykernel_launcher.py:33: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
100%|██████████| 188688/188688 [03:29<00:00, 900.49it/s]

In [21]:
pd.unique(ment['resId']).shape

(192024,)

In [22]:
ment.to_csv(folder+"final_shodhganga_dataset_v5_2_7_1.csv",index=False)

In [23]:
tmp[tmp=='two'].shape

(8858,)

In [32]:
188271-(172747+11108+1019)

3397

In [24]:
tmp[tmp.isnull()].shape

(2946,)

In [34]:
ment.shape

(205744, 28)

In [25]:
ment[ment['researcher_name']=="Singh, Suman"][['advisor_name','title','advId','resId','N_thesisId','thesisId']]

,advisor_name,title,advId,resId,N_thesisId,thesisId
88015,"Dwivedi, Vashishth",Nagarjuna ke katha sahitya mein janwadi chetna,41839,175934,T195748,T195748
88149,"Tiwari, Kamlakar",Bhartiye kavyashastra Aur Kabir ka sahitya,41856,287111,T109841,T109841
88180,"Shastri, Harihar Singh",Dr Rangey Raghav Ke upanyason Aur yugchetna,41860,287112,T147821,T147821
88316,"Singh, Phool Badan",Vyangyakaar Harishankar Parsai Aur unka rachna...,41880,287113,T104617,T104617
88475,"Singh, Kiran",Lokgeet parampara Aur prayog,41932,287114,T179379,T179379
88574,"Pratap, Mahendra",Jain dharm evam baudh dharm mein samaj darshan...,42002,287115,T22914,T22914
104997,"Tripathi, R. N.",Gramin shakti sanrachna tatha gramin sttarikar...,50506,192267,T150317,T150317
105030,"Srivastav, Tej Prakash",Gramin samudaye mein satta sanrachna ke pariva...,50513,192267,T150317,T100428
105229,"Sharma, P. C.",Jaunpur janpad mein bhumi sudhar karyakramo ki...,50612,192737,T3430,T3430
105371,"Pandey, Srikant",Bharat ke aarthik vikas mein pratyaksh videshi...,50683,192995,T47407,T47407
105933,"Singh, Mithilesh Kumar",Land and human resource A geographical study o...,50819,193445,T137129,T137129
106006,"Singh, Devendra Nath",Karanda vikas khand Gazipur mein gramya vikas ...,50833,287447,T163659,T163659
109737,"Singh, Nand Lal",Bulk rheological behaviour of Blood in narrow ...,52428,197164,T172457,T172457
110858,"Dubey, Ajai Kumar",B Ed Prashiksharthiyon ke pratyakshikrit prati...,52833,198190,T125109,T125109
167976,"Singla, M. L.",Synthesis characterization and application of ...,80331,253977,T182277,T182277
176107,"Dubey, Ajay Kumar",B ed prashikshyanaarthion ke pratyakshikrit pr...,83824,262132,T79339,T79339
176189,"Singh, Dasharath",Growth response of certain rabi crop plants to...,83847,262241,T191340,T191340
180337,Banerjee,studies on active principles of lipids from so...,85856,265885,T141770,T141770
200933,"Singh, Balbeer",Tritya saptak mein samajik evam rashtriye chetna,256733,287116,T113688,T113688
201029,"Singh, Ajai Kumar",Morpho taxonomic studies on seedlings of medic...,262276,288613,T173395,T173395

In [26]:
ment[ment['N_thesisId']=="T42107"]

,advisorId,researcherId,advId,resId,advisor_name,researcher_name,publisher_dept,DepartmentId,publisher_institution,instituteId,...,new_date_awarded,dc.date.awarded,dc.subject.ddc,uniq_ddc_across_dept,dc.description.abstract,dc.title.alternative,N_DepartmentId_1,ddc_code,advisor_advId,researcher_resId
17112,7339,7364,7339,7328,"Shastri, Paramanand","Sharma, Satyaprakash",department of sanskrit,D453,Aligarh Muslim University,I292,...,1978-07-01,NaN,400::Language|490::Other languages|491::East I...,"('400', '490', '491')",NaN,NaN,D1989,"('400', '490', '491')","Shastri, Paramanand@7339","Sharma, Satyaprakash@7328"

In [27]:
ment[ment['resId']==93816]#['date_submitted']

,advisorId,researcherId,advId,resId,advisor_name,researcher_name,publisher_dept,DepartmentId,publisher_institution,instituteId,...,new_date_awarded,dc.date.awarded,dc.subject.ddc,uniq_ddc_across_dept,dc.description.abstract,dc.title.alternative,N_DepartmentId_1,ddc_code,advisor_advId,researcher_resId
553,171,93816,171,93816,"Saini, B. K.","Chukwu, Oku Christopher",department of education,D623,Panjab University,I87,...,1993-06-30,NaN,300::Social sciences|370::Education,"('300', '370')",NaN,NaN,D1418,"('300', '370')","Saini, B. K.@171","Chukwu, Oku Christopher@93816"

In [28]:
ment[ment['advId']==63216]

,advisorId,researcherId,advId,resId,advisor_name,researcher_name,publisher_dept,DepartmentId,publisher_institution,instituteId,...,new_date_awarded,dc.date.awarded,dc.subject.ddc,uniq_ddc_across_dept,dc.description.abstract,dc.title.alternative,N_DepartmentId_1,ddc_code,advisor_advId,researcher_resId
130889,63216,217584,63216,4963,Kurup P. A.,"Philip, Babu",department of biochemistry,D753,University of Kerala,I311,...,1978-11-06,NaN,500::Natural sciences & mathematics|540::Chemi...,"('500', '540')",NaN,NaN,D753,"('500', '540')",Kurup P. A.@63216,"Philip, Babu@4963"
130890,63216,217576,63216,63213,Kurup P. A.,Vijayalakshmi N R,department of biochemistry,D753,University of Kerala,I311,...,1975-11-30,NaN,500::Natural sciences & mathematics|540::Chemi...,"('500', '540')",NaN,NaN,D753,"('500', '540')",Kurup P. A.@63216,Vijayalakshmi N R@63213
130891,63216,217479,63216,63227,Kurup P. A.,Indira M,department of biochemistry,D753,University of Kerala,I311,...,1981-07-10,NaN,500::Natural sciences & mathematics|540::Chemi...,"('500', '540')",NaN,NaN,D753,"('500', '540')",Kurup P. A.@63216,Indira M@63227
130892,63216,217618,63216,63230,Kurup P. A.,Muraleedhara Kurup G,department of biochemistry,D753,University of Kerala,I311,...,1985-03-03,NaN,500::Natural sciences & mathematics|540::Chemi...,"('500', '540')",NaN,NaN,D753,"('500', '540')",Kurup P. A.@63216,Muraleedhara Kurup G@63230
130893,63216,217570,63216,63231,Kurup P. A.,Rajamohan T,department of biochemistry,D753,University of Kerala,I311,...,1990-02-28,NaN,500::Natural sciences & mathematics|540::Chemi...,"('500', '540')",NaN,NaN,D753,"('500', '540')",Kurup P. A.@63216,Rajamohan T@63231
130894,63216,217523,63216,63234,Kurup P. A.,Leelamma S,department of biochemistry,D753,University of Kerala,I311,...,1977-10-03,NaN,500::Natural sciences & mathematics|540::Chemi...,"('500', '540')",NaN,NaN,D753,"('500', '540')",Kurup P. A.@63216,Leelamma S@63234
130895,63216,63232,63216,66954,Kurup P. A.,"Abraham, Annie",department of biochemistry,D753,University of Kerala,I311,...,1988-02-19,NaN,500::Natural sciences & mathematics|540::Chemi...,"('500', '540')",NaN,NaN,D753,"('500', '540')",Kurup P. A.@63216,"Abraham, Annie@66954"
130896,63216,217544,63216,67103,Kurup P. A.,Saraswathy Devi K,department of biochemistry,D753,University of Kerala,I311,...,1973-11-02,NaN,500::Natural sciences & mathematics|540::Chemi...,"('500', '540')",NaN,NaN,D753,"('500', '540')",Kurup P. A.@63216,Saraswathy Devi K@67103
130897,63216,217480,63216,217480,Kurup P. A.,Satakopan V N,department of biochemistry,D753,University of Kerala,I311,...,1977-09-10,NaN,500::Natural sciences & mathematics|540::Chemi...,"('500', '540')",NaN,NaN,D753,"('500', '540')",Kurup P. A.@63216,Satakopan V N@217480
130898,63216,217484,63216,217484,Kurup P. A.,Prema L,department of biochemistry,D753,University of Kerala,I311,...,1975-11-15,NaN,500::Natural sciences & mathematics|540::Chemi...,"('500', '540')",NaN,NaN,D753,"('500', '540')",Kurup P. A.@63216,Prema L@217484
130899,63216,217491,63216,217491,Kurup P. A.,"Nambisan, Bala",department of biochemistry,D753,University of Kerala,I311,...,1976-11-15,NaN,500::Natural sciences & mathematics|540::Chemi...,"('500', '540')",NaN,NaN,D753,"('500', '540')",Kurup P. A.@63216,"Nambisan, Bala@217491"
130900,63216,217500,63216,217492,Kurup P. A.,Prasannan K,department of biochemistry,D753,University of Kerala,I311,...,1976-07-06,NaN,500::Natural sciences & mathematics|540::Chemi...,"('500', '540')",NaN,NaN,D753,"('500', '540')",Kurup P. A.@63216,Prasannan K@217492
130901,63216,217508,63216,217508,Kurup P. A.,Vijayagopalan P,department of biochemistry,D753,University of Kerala,I311,...,1973-07-25,NaN,500::Natural sciences & mathematics|540::Chemi...,"('500', '540')",NaN,NaN,D753,"('500', '540')",Kurup P. A.@63216,Vijayagopalan P@217508
130902,63216,217513,63216,217513,Kurup P. A.,Thomas Varghese E,department of biochemistry,D753,University of Kerala,I311,...,1986-06-18,NaN,500::Natural sciences & mathematics|540::Chemi...,"('500', '540')",NaN,NaN,D753,"('500', '540')",Kurup P. A.@63216,Thomas Varghese E@217513
130903,63216,217516,63216,217516,Kurup P. A.,Padma Kumaran Nair K G,department of biochemistry,D753,University of Kerala,I311,...,1998-05-15,NaN,500::Natural sciences & mathematics|540::Chemi...,"('500', '540')",NaN,NaN,D753,"('500', '540')",Kurup P. A.@63216,Padma Kumaran Nair K G@217516
130904,63216,217517,63216,217517,Kurup P. A.,Latha M S,department of biochemistry,D753,University of Kerala,I311,...,1989-12-15,NaN,500::Natural sciences & mathematics|540::Chemi...,"('500', '540')",NaN,NaN,D753,"('500', '540')",Kurup P. A.@63216,Latha M S@217517
130905,63216,217521,63216,217521,Kurup P. A.,Chempakam B,department of biochemistry,D753,University of Kerala,I311,...,1978-11-04,NaN,500::Natural sciences & mathematics|540::Chemi...,"('500', '540')",NaN,NaN,D753,"('500', '540')",Kurup P. A.@63216,Chempakam B@217521
130906,63216,217522,63216,217522,Kurup P. A.,"Menon, Venugopal Padmanabhan",department of biochemistry,D753,University of Kerala,I311,...,1976-11-15,NaN,500::Natural sciences & mathematics|540::Chemi...,"('500', '540')",NaN,NaN,D753,"('500', '540')",Kurup P. A.@63216,"Menon, Venugopal Padmanabhan@217522"
130907,63216,217525,63216,217525,Kurup P. A.,"Abraham, Rita",department of biochemistry,D753,University of Kerala,I311,...,1992-06-24,NaN,500::Natural sciences & mathematics|540::Chemi...,"('500', '540')",NaN,NaN,D753,"('500', '540')",Kurup P. A.@63216,"Abraham, Rita@217525"
130908,63216,217538,63216,217538,Kurup P. A.,Jaya Kumary N,department of biochemistry,D753,University of Kerala,I311,...,1981-03-22,NaN,500::Natural sciences & mathematics|540::Chemi...,"('500', '540')",NaN,NaN,D753,"('500', '540')",Kurup P. A.@63216,Jaya Kumary N@217538
130909,63216,217539,63216,217539,Kurup P. A.,Kumudesan N,department of biochemistry,D753,University of Kerala,I311,...,1989-06-22,NaN,500::Natural sciences & mathematics|540::Chemi...,"('500', '540')",NaN,NaN,D753,"('500', '540')",Kurup P. A.@63216,Kumudesan N@217539
130910,63216,217551,63216,217551,Kurup P. A.,Manojkumar V,department of biochemistry,D753,University of Kerala,I311,...,1998-04-15,NaN,500::Natural sciences & mathematics|540::Chemi...,"('500', '540')",NaN,NaN,D753,"('500', '540')",Kurup P. A.@63216,Manojkumar V@217551
130911,63216,217553,63216,217553,Kurup P. A.,Usha Nair N,department of biochemistry,D753,University of Kerala,I311,...,1993-01-15,NaN,500::Natural sciences & mathematics|540::Chemi...,"('500', '540')",NaN,NaN,D753,"('500', '540')",Kurup P. A.@63216,Usha Nair N@217553
130912,63216,217557,63216,217557,Kurup P. A.,Seetha Ratna Kumari T,department of biochemistry,D753,University of Kerala,I311,...,1991-04-20,NaN,500::Natural sciences & mathematics|540::Chemi...,"('500', '540')",NaN,NaN,D753,"('500', '540')",Kurup P. A.@63216,Seetha Ratna Kumari T@217557
130913,63216,217561,63216,217561,Kurup P. A.,"Koola, Jyothi Junu",department of biochemistry,D753,University of Kerala,I311,...,1999-02-28,NaN,500::Natural sciences & mathematics|540::Chemi...,"('500', '540')",NaN,NaN,D753,"('500', '540')",Kurup P. A.@63216,"Koola, Jyothi Junu@217561"
130914,63216,217568,63216,217568,Kurup P. A.,Prema P,department of biochemistry,D753,University of Kerala,I311,...,1981-04-11,NaN,500::Natural sciences & mathematics|540::Chemi...,"('500', '540')",NaN,NaN,D753,"('500', '540')",Kurup P. A.@63216,Prema P@217568
130915,63216,217579,63216,217579,Kurup P. A.,Arun P,department of biochemistry,D753,University of Kerala,I311,...,1999-06-30,NaN,500::Natural sciences & mathematics|540::Chemi...,"('500', '540')",NaN,NaN,D753,"('500', '540')",Kurup P. A.@63216,Arun P@217579
130916,63216,217581,63216,217581,Kurup P. A.,Deepadevi K V,department of biochemistry,D753,University of Kerala,I311,...,1999-08-28,NaN,500::Natural sciences & mathematics|540::Chemi...,"('500', '540')",NaN,NaN,D753,"('500', '540')",Kurup P. A.@63216,Deepadevi K V@217581
130917,63216,217585,63216,217585,Kurup P. A.,Valsala P,department of biochemistry,D753,University of Kerala,I311,...,1988-10-21,NaN,500::Natural sciences & mathematics|540::Chemi...,"('500', '540')",NaN,NaN,D753,"('500', '540')",Kurup P. A.@63216,Valsala P@217585
130918,63216,217599,63216,217599,Kurup P. A.,Sherief P M,department of biochemistry,D753,University of Kerala,I311,...,1990-06-20,NaN,500::Natural sciences & mathematics|540::Chemi...,"('500', '540')",NaN,NaN,D753,"('500', '540')",Kurup P. A.@63216,Sherief P M@217599
130919,63216,217601,63216,217601,Kurup P. A.,Sreekumar P,department of biochemistry,D753,University of Kerala,I311,...,1978-06-09,NaN,500::Natural sciences & mathematics|540::Chemi...,"('500', '540')",NaN,NaN,D753,"('500', '540')",Kurup P. A.@63216,Sreekumar P@217601
130920,63216,217611,63216,217611,Kurup P. A.,Lakshmi Prabha A N,department of biochemistry,D753,University of Kerala,I311,...,1990-11-01,NaN,500::Natural sciences & mathematics|540::Chemi...,"('500', '540')",NaN,NaN,D753,"('500', '540')",Kurup P. A.@63216,Lakshmi Prabha A N@217611
130921,63216,217612,63216,217612,Kurup P. A.,Malathy K,department of biochemistry,D753,University of Kerala,I311,...,1973-01-17,NaN,500::Natural sciences & mathematics|540::Chemi...,"('500', '540')",NaN,NaN,D753,"('500', '540')",Kurup P. A.@63216,Malathy K@217612
130922,63216,217616,63216,217616,Kurup P. A.,Seethanathan P,department of biochemistry,D753,University of Kerala,I311,...,1972-05-15,NaN,500::Natural sciences & mathematics|540::Chemi...,"('500', '540')",NaN,NaN,D753,"('500', '540')",Kurup P. A.@63216,Seethanathan P@217616
130923,63216,217620,63216,217620,Kurup P. A.,Sandhyavathy Bai L,department of biochemistry,D753,University of Kerala,I311,...,1978-10-20,NaN,500::Natural sciences & mathematics|540::Chemi...,"('500', '540')",NaN,NaN,D753,"('500', '540')",Kurup P. A.@63216,Sandhyavathy Bai L@217620
130924,63216,217626,63216,217626,Kurup P. A.,Suresh Kumar N,department of biochemistry,D753,University of Kerala,I311,...,1988-09-23,1988-09-23,500::Natural sciences & mathematics|540::Chemi...,"('500', '540')",NaN,NaN,D753,"('500', '540')",Kurup P. A.@63216,Suresh Kumar N@217626
130925,63216,217627,63216,217627,Kurup P. A.,Jaya P,department of biochemistry,D753,University of Kerala,I311,...,1989-03-20,1989-03-20,500::Natural sciences & mathematics|540::Chemi...,"('500', '540')",NaN,NaN,D753,"('500', '540')",Kurup P. A.@63216,Jaya P@217627
130926,63216,217636,63216,217636,Kurup P. A.,Ramla,department of biochemistry,D753,University of Kerala,I311,...,NaN,NaN,500::Natural sciences & mathematics|540::Chemi...,"('500', '540')",NaN,NaN,D753,"('500', '540')",Kurup P. A.@63216,Ramla@217636
130927,63216,217520,63216,287730,Kurup P. A.,Vijayakumar S T,department of biochemistry,D753,University of Kerala,I311,...,1977-10-03,NaN,500::Natural sciences & mathematics|540::Chemi...,"('500', '540')",NaN,NaN,D753,"('500', '540')",Kurup P. A.@63216,Vijayakumar S T@217520
130928,63260,217629,63216,287732,"Kurup, Pa","Suresh Kumar, N.",department of biochemistry,D753,University of Kerala,I311,...,NaN,NaN,500::Natural sciences & mathematics|540::Chemi...,"('500', '540')",NaN,NaN,D753,"('500', '540')","Kurup, Pa@63216","Suresh Kumar, N.@217626"

In [29]:
ment[ment['resId'].isnull()]

Empty DataFrame
Columns: [advisorId, researcherId, advId, resId, advisor_name, researcher_name, publisher_dept, DepartmentId, publisher_institution, instituteId, title, thesisId, N_thesisId, date_submitted, new_date_awarded, dc.date.awarded, dc.subject.ddc, uniq_ddc_across_dept, dc.description.abstract, dc.title.alternative, N_DepartmentId_1, ddc_code, advisor_advId, researcher_resId]
Index: []

[0 rows x 24 columns]