In [1]:
import pandas as pd

In [2]:
dataset=pd.read_csv("sodhganaga_dataset.csv",sep=",")

In [5]:
dataset.head()

,advisorId,researcherId,dc.contributor.advisor[],dc.creator.researcher[],dc.date.submitted[],dc.language.iso[],dc.publisher.department[],DepartmentId,dc.publisher.institution[],instituteId,dc.title[],thesisId,dc.type.degree,dc.date.awarded,dc.subject.ddc,dc.source.uri,dc.description.abstract,dc.title.alternative
0,0,38335,"Jose, Joseph","Thoppil, John E.",01-01-1998,eng,department of sacred heart college(thevara). d...,D1321,Mahatma Gandhi University,I251,Chromosome studies and exploration of chemical...,T121508,phd,16-12-1993,500::Natural sciences & mathematics|580::Plant...,http://shodhganga.inflibnet.ac.in/,NaN,NaN
1,1,75893,"Raju, K. V.","Ancy, V P.",29-05-2015,eng,department of sacred heart college,D2490,Mahatma Gandhi University,I251,Fishing industry in Kerala The perils of inter...,T64215,phd,29-03-2016,300::Social sciences,http://shodhganga.inflibnet.ac.in/,NaN,NaN
2,2,75894,"Joseph, K. K.","Sajoy, P B.",24-08-2015,eng,department of sacred heart college,D2490,Mahatma Gandhi University,I251,Savings and investment pattern of stock invest...,T134025,phd,29-03-2016,300::Social sciences,http://shodhganga.inflibnet.ac.in/,NaN,NaN
3,3,75895,"Thomas, E. M.","Leema, T G.",15-07-2015,eng,department of sacred heart college,D2490,Mahatma Gandhi University,I251,An economic analysis of Kole cultivation in Ke...,T78956,phd,02-06-2016,300::Social sciences,http://shodhganga.inflibnet.ac.in/,NaN,NaN
4,4,75896,"Francis, M. S.","Murali, Soumya",28-12-2015,eng,department of sacred heart college,D2490,Mahatma Gandhi University,I251,Phytochemical and Molecular Systematics of Ari...,T54905,phd,05-11-2016,300::Social sciences,http://shodhganga.inflibnet.ac.in/,NaN,NaN

In [7]:
index=pd.read_csv("researcher_index.csv",sep=",")

In [8]:
index.head()

          r_names  rid
0    Jose, Joseph    0
1     Raju, K. V.    1
2   Joseph, K. K.    2
3   Thomas, E. M.    3
4  Francis, M. S.    4

In [ ]:
# for idd in uniq_resid_all:
#     tmp = ment[ment['resId']==idd].copy()
#     if tmp.shape[0]==1:
#         continue
#     else:
#         uniq_thesisid = pd.unique(tmp['N_thesisId'])
#         uniq_resid = pd.unique(tmp['resId'])
#         if uniq_resid.shape[0]==1 and uniq_thesisid.shape[0]==1:
#             continue
#         elif  uniq_resid.shape[0]==1 and uniq_thesisid.shape[0] > 1:
#             as_adv = ment[ment['advId']==idd].copy()
#             as_stud_uniq_thesis = tmp[tmp['N_thesisId'].isin(uniq_thesisid)][['dc.title[]','N_thesisId']]
#             as_adv_uniq_thesis = pd.unique(as_adv['dc.title[]'])
#             score=[]
#             for index, stud in tmp.iterrows():
#                 score_list = [nlp(stud['dc.title[]']).similarity(nlp(adv_thesis)) for adv_thesis in as_adv_uniq_thesis]
#                 score.append((stud['N_thesisId'], sum(score_list)))
#             sorted_score = sorted(score, key=lambda x: x[1])
#             #max_stud = tmp[tmp['dc.title[]']==sorted_score[0][0]]
#             for index, stud1 in tmp.iterrows(): 
#                 if stud['N_thesisId'] != sorted_score[0][0]:
#                     ment.loc[((ment['resId']==stud['resId']) & (ment['N_thesisId']==stud['N_thesisId'])), 'resId']=max(max(ment['resId']), max(ment['advId']))+1
#                 else:
#                     continue
#         else:
#             print("Not Possible")